### ISSUE TITLE
Software support rtos 

### ISSUE THREAD

**Issue by JPB1JPB1** [sparkfun/MicroMod_Teensy_Processor#4]
Dear Team

Great board but what about the software support with rtos low power USB Host wifi/bluetooth, sdio 4 bit mode , and all other features spi/i2c driver optimisation for speedy....
Azur or Thread X are running on it with ISO certification  ? 
Which is the best ready to go on market rtos for it ?

Wiating for your hello and best regards
Jp

**Comment by nseidle** [comment]
Thanks!

We wholly depend on the Teensy core for this product and do not plan to add separate RTOS support. That said, [there is quite a bit](https://www.google.com/search?q=teensy+rtos) of discussion and a few options currently available.
