### ISSUE TITLE
MicroMod and Teensy 4/4.1 Pin Discrepancies

### ISSUE THREAD

**Issue by charliecarver** [sparkfun/MicroMod_Teensy_Processor#5]
I noticed a few discrepancies when matching the MicroMod pinout table to the Teensy 4 card from PJRC:

1. MicroMod pins 37 and 35 are both listed as USBHOST_D+

2. The G0…G4 MicroMod pins are listed as mapping to 40…44 on the Teensy (which aren’t in the Teensy 4 datasheet), and then later listed as:
	• G0 - GPIO pin 15, pad 40 on the MicroMod
	• G1 - GPIO pin 25, pad 42 on the MicroMod
	• G2 - GPIO pin 26, pad 44 on the MicroMod
	• G3 - GPIO pin 17, pad 46 on the MicroMod
	• G4 - GPIO pin 16, pad 48 on the MicroMod
	• G5 - GPIO pin 32, pad 73 on the MicroMod
	• G6 - GPIO pin 33, pad 71 on the MicroMod
However Teensy pins 15/25/26/etc… are already mapped to other pins?

**Comment by nseidle** [comment]
Please link to sources where possible. I think you're talking about:

https://learn.sparkfun.com/tutorials/micromod-teensy-processor-hookup-guide/all#hardware-overview

![image](https://user-images.githubusercontent.com/117102/162062074-7219583d-15c3-4381-9e5e-1cb23ccf7f86.png)

See [schematic](https://cdn.sparkfun.com/assets/5/a/3/6/0/MicroMod-Teensy_V1_3.pdf)
![image](https://user-images.githubusercontent.com/117102/162062326-e51a46fa-856f-4ac1-aad0-6fbbba95100b.png)

Good catch, typo. Should be 37 = D-. Fixed now.

![image](https://user-images.githubusercontent.com/117102/162063431-9ea2e97a-4b63-40a3-ab87-ec764efcd4af.png)

MicroMod Teensy exposes slightly more pins than the Teensy 4. We were *just* able to route to balls B0_04, B0_05, etc from the IMXRT1062DV, best visible in the schematic. These are called pin '40-45' in the Arduino world. These are electrically routed off the MM processor board on M.2 pins 40, 42, 44, 46, 48, 73. Sorry, it's confusing. Said differently, a `digitalWrite(45, HIGH)` should cause G5 (pin 73) on the MicroMod carrier board to go high.

I believe the "G0 - GPIO pin 15, pad 40 on the..." may have been a copy/paste typo. I'll have someone double check it.

Thanks for reporting!

**Comment by nseidle** [comment]
Yep - copy paste error. Should be fixed now.
