### ISSUE TITLE
PID/VID for Teensy Micromod

### ISSUE THREAD

**Issue by mjs513** [sparkfun/MicroMod_Teensy_Processor#6]
A forum post has been generated by @KurtE to assign a PID/VID for the Teensy Micromod board. Saw they were generated for other micromod boards but nothing so far for the Teensy.  Would like to add circuitpython to the board so this is needed.  Please either answer here or on the fourm.

**Comment by nseidle** [comment]
Perhaps I'm confused but @PaulStoffregen assigns the VID/PID according to his HID bootloader and serial port driver. We don't have control over it.

From a quick look,

VID = 0x16C0
PID = 0x0478
PID = 0x0483 (Serial Port mode)

![image](https://user-images.githubusercontent.com/117102/162060842-8fbc6ec9-c759-4113-adbc-4da0842e3e44.png)

![image](https://user-images.githubusercontent.com/117102/162060646-96372178-6c6a-43f8-a59a-57effded83e1.png)

**Comment by KurtE** [comment]
Note: I posted more information in the forum thread: https://forum.sparkfun.com/viewtopic.php?f=182&t=57464&p=232370#p232370
